version: '3.8'

services:
  main:
    build: ./challenge
    ports:
      - "3000:3000"
    environment:
      - FLAG=dice{i_h4t3_java5cript!}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 500M
