version: '3.8'

services:
  filestorage:
    image: filestorage:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: production
    entrypoint: ["sh", "-c", "ls -la /app && cat /app/package.json && npm install && npm start"]
