version: '3.8'

services:
  filestorage:
    image: filestorage:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
